export const GET_CARS_SUCCESS = "GET_CARS_SUCCESS";
export const GET_CARS_ERROR = "GET_CARS_ERROR";
export const GET_CAR_SUCCESS = "GET_CAR_SUCCESS";
export const GET_CAR_ERROR = "GET_CAR_ERROR";

export const BOOK_CAR_SUCCESS = "BOOK_CAR_SUCCESS";
export const BOOK_CAR_ERROR = "BOOK_CAR_ERROR";

export const GET_BOOKINGS_LOADING = "GET_BOOKINGS_LOADING";
export const CANCEL_BOOKING_SUCCESS = "CANCEL_BOOKING_SUCCESS";
export const CANCEL_BOOKING_ERROR = "CANCEL_BOOKING_ERROR";

export const GET_BOOKINGS_SUCCESS = "GET_BOOKINGS_SUCCESS";
export const GET_BOOKINGS_ERROR = "GET_BOOKINGS_ERROR";

export const ADD_CAR_SUCCESS = "ADD_CAR_SUCCESS";
export const ADD_CAR_ERROR = "ADD_CAR_ERROR";

export const DELETE_CAR_SUCCESS = "DELETE_CAR_SUCCESS";
export const DELETE_CAR_ERROR = "DELETE_CAR_ERROR";

export const GET_CAR_BY_ID = "GET_CAR_BY_ID ";
export const GET_CAR_BY_ID_SUCCESS = "GET_CAR_BY_ID_SUCCESS";

export const CLEAR_ERROR = "CLEAR_ERROR";
export const CLEAR_SUCCESS_MESSAGE = "CLEAR_SUCCESS_MESSAGE";
